### ISSUE TITLE
Complete addition of coredns-mdns integration to installer

### ISSUE THREAD

**Issue by russellb** [metalkube/kni-installer#62]
Our integration of coredns-mdns is not specific to the `baremetal` platform.  Before this can be upstreamed to OpenShift, it should be updated to only be run on the platform(s) where it's needed.

**Comment by russellb** [comment]
The installer includes the bootstrap portion of this, but the master integration is in dev-scripts and needs to be moved to the installer.

**Comment by celebdor** [comment]
the master and worker probably belong in the machine-config-operator repo.

**Comment by hardys** [comment]
@celebdor hey any update and/or MCO links we can add to this?

I'm looking at conditionally enabling an ironic staticpod on the bootstrap VM, and wanted to ensure that aligns with how we make the coredns/mdns stuff conditional on the baremetal platform.

**Comment by hardys** [comment]
Ok so after some discussion it sounds like the way forward is to specify some platform-specific ignition additions for the bootstrap node, similar to how the openstack platform is already doing things, ref:

https://github.com/openshift/installer/pull/1746/

https://github.com/openshift/installer/blob/dfaaa42f56945e0cba6a581fd7ed01e135887786/data/data/openstack/bootstrap/main.tf#L19-L56

I'll give this a try and see how it goes unless anyone is already looking into this.

**Comment by celebdor** [comment]
@cybertron (installer) and @bcrochet are on it

**Comment by hardys** [comment]
> @cybertron (installer) and @bcrochet are on it

Ok thanks, I'll hold off moving any of the *dns bits into the terraform templates, but have been trying that as a way to start the ironic staticpod, I'm assuming we can just move all the baremetal specific bits there as a first step, then look at having platform specific installer assets later (which would be useful for UPI cases where you want these files rendered in the `create ignition-configs` output)

**Comment by hardys** [comment]
Hmm actually looking again at this with some help from @dhellmann perhaps we can add a switch to: 

https://github.com/openshift-metal3/kni-installer/blob/master/pkg/asset/ignition/bootstrap/bootstrap.go#L122

Since we already load the InstallConfig there, so we should be able to determine the platform type, and move the platform-specific units/files so we can load them by pattern only for the baremetal platform?

@cybertron any feedback on that - seems like a probably cleaner approach than the terraform additions I was initially considering, and it might fit well for the OpenStack dns integration previously linked, cc @trown

**Comment by hardys** [comment]
https://github.com/openshift-metal3/kni-installer/pull/102 pushed which shows one way to could do this, feedback welcome!
